name: Build & Deploy Flutter App

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Flutter App
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze lib test

      - name: Run Tests
        run: flutter test --no-pub --coverage --test-randomize-ordering-seed random packages test

      - name: Build Android App
        run: flutter build apk

      - name: Build iOS App
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: Build Web App
        run: flutter build web

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: flutter-artifacts
          path: |
            build/app/outputs/**/*.apk
            build/ios/iphoneos/app.ipa
            build/web

  deploy:
    name: Deploy Web & Release Apps
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: flutter-artifacts
          path: artifacts

      - name: Deploy Web to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }}
        working-directory: artifacts/build/web

      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            artifacts/build/app/outputs/**/*.apk,
            artifacts/build/ios/iphoneos/app.ipa
          tag: v1.0.${{ github.run_number }}
